image: electronuserland/builder:wine

cache:
  paths:
    - node_modules/

stages:
  - preparing
  - testing
  - building
  - deploying

install-npm-modules:
  stage: preparing
  script:
    - yarn

run-testcases-with-coverage:
  stage: testing
  script:
    #  設定時區 ( 給測試用)
    - echo 'Asia/Taipei' > /etc/timezone &&
      apt-get update && apt-get install -y tzdata &&
      ln -snf /usr/share/zoneinfo/Asia/Taipei /etc/localtime &&
      dpkg-reconfigure -f noninteractive tzdata

    - yarn test:coverage

build-project-code:
  stage: building
  script:
    - yarn compile

deploy-windows-distributions:
  stage: deploying
  only:
    - tags
  script:
    - yarn dist:win
  artifacts:
    name: "dist"
    expire_in: 1 day
    paths:
      - $CI_PROJECT_DIR/dist
